#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
case $BRANCH in
    master)
        echo "Merging janner with master"
        if !(git checkout janner && git pull && git merge master && git push); then
            echo "ABORTING, unable to merge with master"
            git checkout master 1>/dev/null
            exit 1
        fi
        git checkout master 1>/dev/null
        ;;
esac
